# Generated by GitHub Copilot on 2026-04-11

import django.db.models.deletion
from django.db import migrations, models
import mptt.fields


def _init_mptt_fields(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')

    tasks = list(Task.objects.order_by('id'))
    for idx, task in enumerate(tasks, start=1):
        task.tree_id = idx
        task.lft = 1
        task.rght = 2
        task.level = 0

    if tasks:
        Task.objects.bulk_update(tasks, ['tree_id', 'lft', 'rght', 'level'])


def _noop_reverse(apps, schema_editor):
    # No safe reverse for tree field initialization.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_project_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['tree_id', 'lft']},
        ),
        migrations.RunPython(_init_mptt_fields, reverse_code=_noop_reverse),
    ]
