# Generated by Django 5.2.13 on 2026-04-11 09:51

import secrets

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_project_invite_codes(apps, schema_editor):
    Project = apps.get_model('tasks', 'Project')

    # Ensure all existing projects get a shareable invite code.
    for project in Project.objects.filter(invite_code__isnull=True):
        for _ in range(10):
            candidate = secrets.token_urlsafe(9)[:12]
            if not Project.objects.filter(invite_code=candidate).exists():
                project.invite_code = candidate
                project.save(update_fields=['invite_code'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_mptt_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invite_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.RunPython(populate_project_invite_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tasks.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
    ]
